apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rps-app
  template:
    metadata:
      labels:
        app: rps-app
    spec:
      containers:
        - name: rps-container
          image: ${{ env.DOCKER_IMAGE }}
          ports:
            - containerPort: 8080
