# Name of the workflow
name: Build and Deploy

# Trigger the workflow on a push event to the main or dev branch
on:
  push:
    branches:
      - "*"

# Define jobs for the workflow
jobs:
  build-and-push:
    # Use the latest Ubuntu image as the build environment
    runs-on: ubuntu-latest

    # Define the steps for the job
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub and ghcr using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username stored as a secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password stored as a secret

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image and tag it with the git commit hash and ghcr.io registry
      - name: Build and tag Docker image
        run: |
          # Build the Docker image and tag it with the git commit hash
          docker build -t patrickgoulding/flexport-takehome:${{ github.sha }} .

          # Tag the Docker image for the ghcr.io registry
          docker tag patrickgoulding/flexport-takehome:${{ github.sha }} ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.sha }}

      # Step 3: Push the Docker image to the registry
      - name: Push Docker image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            patrickgoulding/flexport-takehome:${{ github.sha }}
            ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.sha }}

  kind:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kind create cluster --name rps-flexport
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Deploy Application
        run: |
          docker pull ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.sha }}
          kind load docker-image ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.sha }} --name rps-flexport
          kubectl create deployment flexport-takehome --image=ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.sha }}
          kubectl wait pods --for condition=Ready --timeout=90s --all
          kubectl expose deployment/flexport-takehome --type=NodePort --port 5000
      - name: Test Deployment
        run: |
          export NODE_PORT=$(kubectl get services/flexport-takehome -o go-template='{{(index .spec.ports 0).nodePort}}')
          echo NODE_PORT=${NODE_PORT}
          kubectl describe services/flexport-takehome
          export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
          export ENDPOINT=$(kubectl describe services/flexport-takehome | awk '/Endpoints/ {print $2}')
          echo POD_NAME=${POD_NAME}
          echo ENDPOINT =${ENDPOINT}
          kubectl port-forward $POD_NAME 5000:5000 & 
          sleep 5
          wget http://localhost:5000/health -O -
      - name: Test Deployed Enpdoints
        run: |
          PYTHONPATH="${PYTHONPATH}:./src" python -m pytest -v tests/integration
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name rps-flexport
