name: "Kubernetes Deployment"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      # Creates local cluster on kind
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Wait all cluster ready
        run: |
          kubectl wait nodes --for condition=Ready --all

      - name: App deployment and expose the port
        run: |
          kubectl create deployment flexport-app --image=ghcr.io/${{ github.repository }}:main
          kubectl wait pods --for condition=Ready --all --timeout=240s

          kubectl expose deployment/flexport-app --type=NodePort --port 3000

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test deployment
        run: |
          kubectl get services/flexport-app -o go-template='{{(index .spec.ports 0).nodePort}}'
          kubectl port-forward service/flexport-app 3000:3000 > /dev/null

      - name: Run test
        run: |
          PYTHONPATH="${PYTHON_PATH}:./src" python -m pytest -v tests/integration
          python -m pytest -v ./tests/integration/test_integration.py

      - name: Generate coverage report
        run: |
          coverage report -m

      - name: Delete cluster
        if: always()
        run: |
          kind delete cluster --name flexport-app
