name: Deploy to K8s

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v2

      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Deploy RPS
        env:
          GHCR_TOKEN: ${{ secrets.gh_tok }}
        run: |
          echo 'apiVersion: v1
          kind: Secret
          metadata:
            name: ghcr-auth
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: '${{ secrets.GHCR_TOKEN }}'' > ghcr-auth-secret.yaml
          kubectl apply -f ghcr-auth-secret.yaml
          echo 'apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: rps-app
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: rps-app
          template:
            metadata:
              labels:
                app: rps-app
            spec:
              containers:
              - name: rps-app
                image: ghcr.io/okhan98/flexport-devx-takehome:latest
              imagePullSecrets:
              - name: ghcr-auth' > rps-app-deployment.yaml
          kubectl apply -f rps-app-deployment.yaml
          kubectl wait pods --for condition=Ready --timeout=90s --all
          kubectl expose deployment/rps-app --type=NodePort --port 8080

      - name: Run Integration Tests
        run: pytest --cov=src --cov-report=xml tests/functional/

      - name: Test Deployment
        run: |
          export NODE_PORT=$(kubectl get services/rps-app -o go-template='{{(index .spec.ports 0).nodePort}}')
          echo NODE_PORT=${NODE_PORT}
          kubectl describe services/rps-app
          export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
          kubectl exec -ti $POD_NAME -- curl localhost:8080/version

      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd