name: Deploy on K8s

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kind (Kubernetes in Docker)
        uses: engineerd/setup-kind@v1.4.0

      - name: Deploy to Kubernetes
        run: |
          kubectl kustomize k8s | kubectl apply -f -
          kubectl rollout status deployment/my-deployment
        env:
          DOCKER_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Run integration tests
        run: pytest --cov=src --cov-report=xml tests/functional/

      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd