name: Deploy on K8s

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REPOSITORY: ${{ github.repository_owner }}/${{ github.repository_name }}
  DOCKER_TAG: ${{ github.sha }}
  DOCKER_IMAGE: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ env.DOCKER_TAG }}

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Deploy Application
        run: |
          kubectl create deployment kubernetes-bootcamp --image=${{ env.DOCKER_IMAGE }}
          kubectl wait pods --for condition=Ready --timeout=90s --all
          kubectl expose deployment/kubernetes-bootcamp --type=NodePort --port 8080

      - name: Test Deployment
        run: |
          export NODE_PORT=$(kubectl get services/kubernetes-bootcamp -o go-template='{{(index .spec.ports 0).nodePort}}')
          echo NODE_PORT=${NODE_PORT}
          kubectl describe services/kubernetes-bootcamp
          export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
          kubectl exec -ti $POD_NAME -- curl localhost:8080/version

      - name: Run Unit Tests
        run: pytest --cov=src --cov-report=xml tests/functional/

      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd