
name: Build and Publish Container Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghrc.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ghrc.io/${{ github.repository }}:latest
      - name: Run tests
        run: docker run -p 5000:5000 ghrc.io/${{ github.repository }}:latest python -m unittest discover -v
      - name: Publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghrc.io/${{ github.repository }}:latest
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
