name: "deliver to Kubernetes"
on:
  workflow_run:
    workflows: [Build Docker Image]
    types:
      - completed

jobs:
  kind:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Deploy Application
        run: |
          kubectl create deployment rps-app --image=ghcr.io/${{ github.repository }}:main
          kubectl wait pods --for condition=Ready --timeout=90s --all
          kubectl expose deployment/rps-app --type=NodePort --port 5000
      - name: Test Deployment
        run: |
          kubectl describe services/rps-app
          export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
          kubectl exec -ti $POD_NAME -- curl --fail localhost:5000/health
          kubectl exec -ti $POD_NAME -- curl --fail -X POST -H 'Content-Type: application/json' localhost:5000/rps -d '{"move": "Rock"}' 
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd
