name: "deliver to Kubernetes"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Deploy Application
        run: |
          kubectl create deployment flexport-devx-takehome --image=ghcr.io/xinyuxinyuye/flexport-devx-takehome:main
          kubectl wait pods --for condition=Ready --timeout=90s --all
          kubectl expose deployment/flexport-devx-takehome --type=NodePort --port 5000
      - name: Test Deployment
        run: |
          kubectl get services/flexport-devx-takehome
          export IP=$(kubectl get services/flexport-devx-takehome -o go-template='{{.spec.clusterIP}}')
          export NODE_PORT=$(kubectl get services/flexport-devx-takehome -o go-template='{{(index .spec.ports 0).nodePort}}')
          echo $IP:$NODE_PORT
          kubectl describe services/flexport-devx-takehome
          export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
          curl --fail ${IP}:${NODE_PORT}/health
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd
