name: "Test k8s with Kind"
on: [pull_request, push]

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Test Workflow
        run: |
          echo "Waiting for previous action"
          sleep 5
  kind:
    needs: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Deploy Application
        run: |
          kubectl create deployment flexport-takehome --image=ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.sha }}
          kubectl wait pods --for condition=Ready --timeout=90s --all
          kubectl expose deployment/flexport-takehome --type=NodePort --port 8080
      - name: Test Deployment
        run: |
          export NODE_PORT=$(kubectl get services/flexport-takehome -o go-template='{{(index .spec.ports 0).nodePort}}')
          echo NODE_PORT=${NODE_PORT}
          kubectl describe services/flexport-takehome
          export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
          kubectl exec -ti $POD_NAME -- curl localhost:8080/version
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd
