name: Lint and Test

on:
  push:
    branches:
      - '*'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
    steps:
      - name: Get Repository
        uses: actions/checkout@v2

      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Requirements
        run: |
          pip3 install -r requirements.txt

      - name: Code Format Check With Black
        run: black --check .

      - name: Lint Check with Pylint
        run: pylint --fail-under=9 src

      - name: Run Unit Tests
        run: pytest --cov=src --cov-report=xml tests/unit/
