name: Lint and Test
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U -r requirements.txt
        pip install pylint black pytest
        pip install pytest-cov
        export URL=http://localhost:5000
    - name: Run black and pylint
      run: |
        black ./
        pylint **/*.py
    - name: Run Unit Tests with coverage
      run: |
        PYTHONPATH="${PYTHON_PATH}:./src" coverage run -m pytest -v tests/unit
    - name: Run Functional Tests with coverage
      run: |
        PYTHONPATH="${PYTHON_PATH}:./src" coverage run -m pytest -v tests/functional
    - name: Get coverage report
      run: coverage report -m
  