name: lint_and_execute_unit_test

on: [push]      # This workflow will be initiated for every file that is pushed to the repository.

jobs:

  lint_and_execute_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
           python-version: '3.9.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: check formatting
        run: |
          black --diff .  # Here --diff flag only shows diff of changes it would make
          black .         # Here black modifies all python files recursively in current directory

      - name: lint code
        run: find ./  -name "*.py" -exec pylint {} +  # lint all python files recursively in current directory
        continue-on-error: true
        # lint fails for syntax errors, style corrections and etc, then workflow will also fail. Hence added continue-on-error to be true.
        # TODO: fail workflow if errors encountered by pylint otherwise developer has to decide corrections needed for warnings thrown by pylint.

      # performing code coverage only for unit and functional tests
      - name: code coverage
        run: |
          PYTHONPATH="./src" coverage run -m pytest tests/unit
          PYTHONPATH="./src" coverage run -m pytest tests/functional
          PYTHONPATH="./src" coverage report -m | grep -e 'src' -e 'tests/'
          # TODO: fail workflow if coverage report is not above certain percentage based on team's/organsation's standard.
